### ISSUE TITLE
Error when trying to start the app

### ISSUE THREAD

**Issue by mateush** [abogacki/make-a-note#6]
Hey, I'm getting the following error when trying to start the app:

server_1  | [nodemon] starting `ts-node -r tsconfig-paths/register ./src/index.ts`
server_1  | 
server_1  | /server/node_modules/ts-node/src/index.ts:513
server_1  |     return new TSError(diagnosticText, diagnosticCodes)
server_1  |            ^
server_1  | TSError: ⨯ Unable to compile TypeScript:
server_1  | src/controllers/notesController.ts(65,19): error TS2339: Property 'token' does not exist on type 'Request<ParamsDictionary, any, any, ParsedQs, Record<string, any>>'.
server_1  | 
server_1  |     at createTSError (/server/node_modules/ts-node/src/index.ts:513:12)
server_1  |     at reportTSError (/server/node_modules/ts-node/src/index.ts:517:19)
server_1  |     at getOutput (/server/node_modules/ts-node/src/index.ts:752:36)
server_1  |     at Object.compile (/server/node_modules/ts-node/src/index.ts:968:32)
server_1  |     at Module.m._compile (/server/node_modules/ts-node/src/index.ts:1056:42)
server_1  |     at Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
server_1  |     at Object.require.extensions.<computed> [as .ts] (/server/node_modules/ts-node/src/index.ts:1059:12)
server_1  |     at Module.load (internal/modules/cjs/loader.js:996:32)
server_1  |     at Function.Module._load (internal/modules/cjs/loader.js:896:14)
server_1  |     at Module.require (internal/modules/cjs/loader.js:1036:19)
server_1  | [nodemon] app crashed - waiting for file changes before starting...

**Comment by abogacki** [comment]
Thanks for the input. There was an issue with configuration, which was not mentioned in official docs. Should be fixed now. Closing
